/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import java.sql.Connection;
import java.sql.DriverManager;

//...

public class App {

    //...

    public static void main(String[] args) {
        // Test MySQL database connection
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sys", "root", "25352Riigdii")) {
            
            System.out.println("Connected to MySQL database!");
        } catch (Exception e) {
            System.err.println("Failed to connect to MySQL database.");
            e.printStackTrace();
        }

        //...
    }
}
